export const cloudCodes = {
  FEW: 'Few',
  OVC: 'Overcast',
  SCT: 'Scattered',
  BKN: 'Broken',
  SKC: 'Clear Sky',
  OVX: 'obscured',
};

export const wxCodes = {
  '-': 'Slight',
  '+': 'Heavy',
  BC: 'Patches',
  BL: 'Blowing',
  BR: 'Mist',
  DR: 'Low Drifting',
  DS: 'Dust Storm',
  DU: 'Widespread Dust',
  DZ: 'Drizzle',
  FG: 'Fog',
  FC: 'Funnel Cloud',
  FU: 'Smoke',
  FZ: 'Freezing',
  GR: 'Hail',
  GS: 'Small Hail',
  HZ: 'Haze',
  IC: 'Ice Crystals',
  MI: 'Shallow',
  PL: 'Ice Pellets',
  PO: 'Dust Devils',
  RA: 'Rain',
  SA: 'Sand',
  SG: 'Snow Grains',
  SH: 'Shower',
  SN: 'Snow',
  SQ: 'Squall',
  SS: 'Sandstorm',
  TS: 'Thunderstorm',
  VA: 'Volcanic Ash',
  VC: 'In the vicinity',
};
